name: "Espressif IoT Development Framework (ESP-IDF)"
description: "This action builds your firmware for ESP32 directly in GitHub using Espressif ESP-IDF Docker image."
branding:
  color: red
  icon: wifi
inputs:
  path:
    description: "Relative path under $GITHUB_WORKSPACE to place the repository"
    default: ""
    required: false
  esp_idf_version:
    description: "Version of ESP-IDF docker image to use"
    default: "latest"
    required: false
  target:
    description: "ESP32 variant to build for"
    default: "esp32"
    required: false
  command:
    description: "Command to run inside the docker container (default: builds the project)"
    default: "idf.py build"
    required: false

on:
  push:
    branches: [ main ]  # Replace 'main' with your desired branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Build Environment
        run: |
          IDF_TARGET=$(echo "${{ inputs.target }}" | tr '[:upper:]' '[:lower:]' | tr -d '_-')
          docker run --rm -v "${{ github.workspace }}:/project" -w "/project/${{ inputs.path }}" \
          -u $(id -u):$(id -g) -e HOME=/tmp espressif/idf:${{ inputs.esp_idf_version }} \
          /bin/bash -c 'echo "Setting up Git..."; git config --global --add safe.directory "*" && echo "Running command..."; ${{ inputs.command }}'
