on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
      - "release/**"
      - "hotfix/**"

env:
  GITVERSION: "gittools/gitversion:5.10.0-alpine.3.14-6.0"
  MAIN_BRANCHES: ("develop" "main")
  GITVERSION_TAG_PROPERTY_PULL_REQUESTS: .SemVer
  GITVERSION_TAG_PROPERTY_DEFAULT: .SemVer
  GITVERSION_TAG_PROPERTY_DEVELOP: .MajorMinorPatch,.PreReleaseLabelWithDash
  GITVERSION_TAG_PROPERTY_RELEASE: .MajorMinorPatch,.PreReleaseLabelWithDash
  GITVERSION_TAG_PROPERTY_HOTFIX: .MajorMinorPatch,.PreReleaseLabelWithDash
  GITVERSION_TAG_PROPERTY_MAIN: .MajorMinorPatch

jobs:
  gitversion:
    name: gitversion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --unshallow && git checkout develop && git checkout main

      - name: Checkout to branch
        run: |
          if [ "${GITHUB_EVENT_NAME}" = 'push' ]; then
            DIFF_DEST="${GITHUB_REF_NAME}"
          else
            DIFF_DEST="${GITHUB_HEAD_REF}"
          fi
          git checkout ${DIFF_DEST}

      - name: Calculate changed files
        id: calculate_changed_files
        run: |
          if [ "${GITHUB_EVENT_NAME}" = 'push' ]; then
            DIFF_DEST="${GITHUB_REF_NAME}"
            DIFF_SOURCE=$(git rev-parse "${DIFF_DEST}"^1)
          else
            DIFF_DEST="${GITHUB_HEAD_REF}"
            DIFF_SOURCE="${GITHUB_BASE_REF}"
          fi
          # use main as source if current branch is a release branch
          if [ "$(echo "${DIFF_DEST}" | grep -o '^release/')" = "release/" ]; then
            DIFF_SOURCE="main"
          fi
          # use main as source if current branch is a hotfix branch
          if [ "$(echo "${DIFF_DEST}" | grep -o '^hotfix/')" = "hotfix/" ]; then
            DIFF_SOURCE="main"
          fi

          # calculate changed files
          changed_files=$(git diff "${DIFF_SOURCE}" "${DIFF_DEST}" --name-only | grep -v '^.github/' | sort | uniq)
          changed_files=$(printf '%s' "$changed_files" | jq --raw-input --slurp '.')
          echo "::set-output name=changed_files::$changed_files"
          echo "::set-output name=diff_source::$DIFF_SOURCE"
          echo "::set-output name=diff_dest::$DIFF_DEST"
          echo "DIFF_SOURCE='$DIFF_SOURCE'"
          echo "DIFF_DEST='$DIFF_DEST'"
          echo "changed_files='$(echo "$changed_files" | sed 'N;s/\n/, /g')'"

      - name: Calculate file versions
        id: calculate_file_versions
        run: |
          changed_files=( ${{ fromJSON(steps.calculate_changed_files.outputs.changed_files) }} )
          if [ "${#changed_files[@]}" = "0" ]; then
            file_versions_txt='## impact surface\nNo files changed\n'
          else
            file_versions_txt="## impact surface\n"
            for file in "${changed_files[@]}"; do
              echo "calculation for ${file}"
              docker run --rm -v "$(pwd):/repo" ${GITVERSION} /repo /config "/repo/.gitversion.yml"
              gitversion_calc=$(docker run --rm -v "$(pwd):/repo" ${GITVERSION} /repo /config "/repo/.gitversion.yml")
              GITVERSION_TAG_PROPERTY_NAME="GITVERSION_TAG_PROPERTY_PULL_REQUESTS"
              GITVERSION_TAG_PROPERTY=${!GITVERSION_TAG_PROPERTY_NAME}
              file_version=$(echo "${gitversion_calc}" | jq -r "[${GITVERSION_TAG_PROPERTY}] | join(\"\")")
              file_versions_txt+="- ${file} - v${file_version}\n"
            done
          fi
          # fix multiline variables
          # from: https://github.com/actions/create-release/issues/64#issuecomment-638695206
          PR_BODY="${file_versions_txt}"
          PR_BODY=$(printf '%s' "$PR_BODY" | jq --raw-input --slurp '.')
          echo "${PR_BODY}"
          echo "::set-output name=PR_BODY::$PR_BODY"

      - name: Update PR description
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          # from https://github.com/actions/checkout/issues/58#issuecomment-614041550
          jq -nc '{"body": "${{ fromJSON(steps.calculate_file_versions.outputs.PR_BODY) }}" }' | \
          curl -sL  -X PATCH -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER"

      - name: Tag build
        if: ${{ github.event_name == 'push' && (startsWith(steps.calculate_changed_files.outputs.diff_dest, 'release') || startsWith(steps.calculate_changed_files.outputs.diff_dest, 'hotfix') || contains(env.MAIN_BRANCHES, steps.calculate_changed_files.outputs.diff_dest)) }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          changed_files=( ${{ fromJSON(steps.calculate_changed_files.outputs.changed_files) }} )
          for file in "${changed_files[@]}"; do
            echo "calculation for ${file}"
            docker run --rm -v "$(pwd):/repo" ${GITVERSION} /repo /config "/repo/.gitversion.yml"
            gitversion_calc=$(docker run --rm -v "$(pwd):/repo" ${GITVERSION} /repo /config "/repo/.gitversion.yml")
            GITVERSION_TAG_PROPERTY_NAME="GITVERSION_TAG_PROPERTY_$(echo '${{ steps.calculate_changed_files.outputs.diff_dest }}' | sed 's|/.*$||' | tr '[[:lower:]]' '[[:upper:]]')"
            GITVERSION_TAG_PROPERTY=${!GITVERSION_TAG_PROPERTY_NAME}
            file_version=$(echo "${gitversion_calc}" | jq -r "[${GITVERSION_TAG_PROPERTY}] | join(\"\")")
            file_without_prefix=$(basename "${file}")
            if [ "${GITVERSION_TAG_PROPERTY}" != ".MajorMinorPatch" ]; then
              previous_commit_count=$(git tag -l | grep "^${file_without_prefix}/v$(echo "${gitversion_calc}" | jq -r ".MajorMinorPatch")-$(echo "${gitversion_calc}" | jq -r ".PreReleaseLabel")" | grep -o -E '\.[0-9]+$' | grep -o -E '[0-9]+$' | sort -nr | head -1)
              next_commit_count=$((previous_commit_count+1))
              full_file_version="${file_version}.${next_commit_count}"
            else
              full_file_version="${file_version}"
            fi
            git tag -a "${file_without_prefix}/v${full_file_version}" -m "${file_without_prefix}/v${full_file_version}"
            git push origin "${file_without_prefix}/v${full_file_version}"
          done
