name: Build ESP-IDF Project

on:
  push:
    branches: [main] # Replace 'main' with your desired branch
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build ESP-IDF Project
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            -w /project \
            -e HOME=/tmp \
            -e BINARY_VERSION=${{ github.ref_name }} \
            espressif/idf:latest \
            /bin/bash -c "idf.py build"

      - name: Set permissions for build output
        run: sudo chown -R $USER:$USER build/

      - name: Create action_build directory
        run: mkdir -p action_build

      - name: Move blink.bin to action_build directory
        run: mv build/blink.bin action_build/

      - name: Upload blink.bin artifact
        uses: actions/upload-artifact@v3
        with:
          name: blink-bin
          path: action_build/blink.bin
