name: "Build ESP-IDF Project"

on: 
  push:
    branches: [ main ]  # Replace 'main' with your desired branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: espressif/idf:latest
          options: -v ${{ github.workspace }}:/project -w /project
          run: |
            echo "Setting up Git..."
            git config --global --add safe.directory "*"
            echo "Running command..."
            idf.py build
